routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('/');

Route::resource('frontend','HomeController');
Route::get('add','Cart\CartController@addToCart')->name('home.add');


Auth::routes();

Route::get('show', 'HomeController@show')->name('home.show');


Route::resource('categories', 'CategoryController')->middleware('admin');
Route::resource('products', 'ProductController')->middleware('admin');
Route::post('products/search','ProductController@search')->name('products.search');


Route::resource('types', 'TypeController')->middleware('admin');


Route::any('cart', 'Cart\CartController@addTocart')->name('cart.index');
Route::any('category/cart', 'Cart\CartController@addTocart')->name('cart.index');

Route::any('cartToOrder', 'Cart\CartController@cartToOrder')->name('cart.order');

Route::get('orders', 'Cart\CartController@order')->name('orders.index')->middleware('admin');

Route::post('orders/complete', 'Cart\CartController@complete')->name('orders.complete')->middleware('admin');

Route::post('orders/delete', 'Cart\CartController@delete')->name('orders.delete')->middleware('admin');


Route::get('customers','Auth\RegisterController@index')->name('customers.index');


Route::resource('users','Auth\RegisterController');
Route::resource('home','HomeController');
Route::any('category/{id}','HomeController@category')->name('home.category');

Route::post('search', "HomeController@search")->name('search');

Route::post('user/edit','HomeController@useredit')->name('/edit');
Route::post('user/update','HomeController@userupdate')->name('update');

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Cart\Cart;
use App\Repositories\CartRepository;
use App\User;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Type;
use App\Models\Category;
use App\Repositories\CategoryRepository;
use App\Repositories\TypeRepository;
use Illuminate\Support\Facades\Input;
use App\Repositories\ProductRepository;
use Illuminate\Support\Facades\Session;


class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    private $productRepository;
    private $typeRepository;


    public function __construct(TypeRepository $typeRepo,ProductRepository $productRepo )
    {
        $this->typeRepository = $typeRepo;
        $this->productRepository = $productRepo;
    } 

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Initialize cart object
        $cart = new Cart([
            // Maximum item can added to cart, 0 = Unlimited
            'cartMaxItem' => 0,

            // Maximum quantity of a item can be added to cart, 0 = Unlimited
            'itemMaxQuantity' => 5,

            // Do not use cookie, cart items will gone after browser closed
            'useCookie' => false,
        ]);
        Session::forget('login');
        $total = $cart->getTotalItem();
        $products = Product::with('types')->get();
        $types    = Type::get();
        return view('home.index',compact('total','products','types'))->withId('');

    }

    public function show($id)

    {
         $products = $this->productRepository->getById($id);
                 // dd($products);

        return view('home.detail', compact('products'));
    }

     public function category($id)

    {
        // dd('aa');
         

                 // Initialize cart object
        $cart = new Cart([
            // Maximum item can added to cart, 0 = Unlimited
            'cartMaxItem' => 0,

            // Maximum quantity of a item can be added to cart, 0 = Unlimited
            'itemMaxQuantity' => 5,

            // Do not use cookie, cart items will gone after browser closed
            'useCookie' => false,
        ]);
        Session::forget('login');
        $total = $cart->getTotalItem();
        $products = Product::where('type_id',$id)->with('types')->get();
        $types    = Type::get();
        return view('home.category',compact('total','products','types'))->withId('');

    }
    public function search(Request $request){
        // Initialize cart object
        $cart = new Cart([
            // Maximum item can added to cart, 0 = Unlimited
            'cartMaxItem' => 0,

            // Maximum quantity of a item can be added to cart, 0 = Unlimited
            'itemMaxQuantity' => 5,

            // Do not use cookie, cart items will gone after browser closed
            'useCookie' => false,
        ]);
        Session::forget('login');
        $total = $cart->getTotalItem();
        $types    = Type::get();
        $search = $request->product;
        $products = Product::with('types')->where('name','LIKE', '%'.$search.'%')->get();
        return view('home.search',compact('total','products','types'))->withId('');
    }
    public function useredit(Request $request)
    {
        // Initialize cart object
        $cart = new Cart([
            // Maximum item can added to cart, 0 = Unlimited
            'cartMaxItem' => 0,

            // Maximum quantity of a item can be added to cart, 0 = Unlimited
            'itemMaxQuantity' => 5,

            // Do not use cookie, cart items will gone after browser closed
            'useCookie' => false,
        ]);
        Session::forget('login');
        $total = $cart->getTotalItem();
        $user = User::where('id', $request->id)->first();
//        dd($user);
        return view('home.user_edit')->with(['total' => $total, 'user' => $user]);
    }
    public function userupdate(Request $request)
    {
        $user = User::where('id', $request->id)->first();
        $user->name = $request->name;
        $user->address = $request->address;
        $user->phone = $request->phone;

        $user->save();

        return redirect('/')->with(['update' => 'Update Successfully']);
    }
}

resources/views/home/category.blade.php
@extends('layouts.frontend')

@section('content')




    <!-- PRODUCTS Start
================================================== -->

    <section id="products">
        <div class="container">
             <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav nav-main">
                    <li class="{{ Request::segment(1) === 'home' || Request::segment(1) == ''? 'active' : null }}"><a href="{{ route('home.index')}}">Home</a></li>
                     @foreach ($types as $type)
                    <li class="{{ Request::segment(2) == $type->id ? 'active' : null }}"><a href="{!! route('home.category', [$type->id]) !!}">{{ $type->name }}</a></li>
                    @endforeach
                </ul> <!-- End of /.nav-main -->
            </div>  
            <div class="row">
                <div class="col-md-12">
                    <div class="products-heading">
                        <br>
                        <h4>NEW PRODUCTS</h4>
                    </div>
                </div>
            </div>
            <div class="row">
                <br>
                @foreach ($products as $product)
                    <div class="col-md-3">
                        <div class="panel panel-default">
                            <a href="{{ route('frontend.show',$product->id)}}">
                                <img src="{{asset($product->image)}}" width="200" height="150">
                            </a>
                            <a href="{{ route('frontend.show',$product->id)}}">
                                <h4>{!! $product->name !!}</h4>
                            </a>
                            <p class="price">{!! $product->price !!} Ks</p>

                            <div class="row">
                                <div class="col-md-5 col-md-offset-1">
                                    <input type="number" value="1" class="form-control qty"/>

                                </div>
                                <input type="hidden" value="{{ $product->id }}" class="form-control id">
                                <input type="hidden" value="{{ $product->price }}" class="form-control price">
                                <input type="hidden" value="{{ $product->name }}" class="form-control name">
                                <div class="col-md-6">
                                    <button class="btn btn-primary add-to-cart"><i class="fa fa-shopping-cart"></i> Add
                                        to Cart
                                    </button>
                                </div>

                            </div>
                        </div>  <!-- End of /.products -->
                    </div>
            @endforeach <!-- End Of /.Col-md-3 -->
            </div>  <!-- End of /.row -->
        </div>  <!-- End of /.container -->
    </section>  <!-- End of Section -->


@endsection

    
   

        

resources/views/home/detail.blade.php
<!DOCTYPE html>

<html lang="en">

<head>

  <title>Okkar Thiri</title>

  <meta charset="utf-8">

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</head>

<body>

 
<div class="container">
	<br>

  <h2>Product Detail Description</h2>

  <div class="card">

    <div class="card-header" align="center">{!! $products->name !!}</div>

    <div class="card-body">
    	<div class="container" align="center">
    		<img src="{{asset($products->image)}}">
    	</div>
    </div> 

    
		<div class="container" align="center">
    		<b>Price      :</b>  {!! $products->price !!}
    		<br>
    		<b>Category :</b>{!! $products->types['name'] !!}

    		<br>
    		<b>Description :</b> <p> {!! $products->description !!}</p>

    	</div>
    <div class="card-footer">
      <div class="container" align="center">
      	<a href="{!! route('home.index') !!}" class="btn btn-info">Back</a>
      </div>	
    	
    </div>

  </div>

</div>

​

</body>

</html>

​

resources/views/home/index.blade.php
@extends('layouts.frontend')

@section('content')




    <!-- PRODUCTS Start
================================================== -->

    <section id="products">
        <div class="container">
             <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav nav-main">
                    <li class="{{ Request::segment(1) === 'home' || Request::segment(1) == '' ? 'active' : null }}"><a href="{{ route('home.index')}}">Home</a></li>
                     @foreach ($types as $type)
                   

                    <li class="{{ Request::segment(2) == $type->id ? 'active' : null }}">
                          <a href="{!! route('home.category', [$type->id]) !!}">{{ $type->name }}</a>
                    </li>
                    @endforeach
                </ul> <!-- End of /.nav-main -->
            </div>  
            <div class="row">
                <div class="col-md-12">
                    <div class="products-heading">
                        <br>
                        <h4>NEW PRODUCTS</h4>
                    </div>
                </div>
            </div>
            <div class="row">
                <br>
                @foreach ($products as $product)
                    <div class="col-md-3">
                        <div class="panel panel-default">
                            <a href="{{ route('frontend.show',$product->id)}}">
                                <img src="{{asset($product->image)}}" width="200" height="150">
                            </a>
                            <a href="{{ route('frontend.show',$product->id)}}">
                                <h4>{!! $product->name !!}</h4>
                            </a>
                            <p class="price">{!! $product->price !!} Ks</p>

                            <div class="row">
                                <div class="col-md-5 col-md-offset-1">
                                    <input type="number" value="1" class="form-control qty"/>

                                </div>
                                <input type="hidden" value="{{ $product->id }}" class="form-control id">
                                <input type="hidden" value="{{ $product->price }}" class="form-control price">
                                <input type="hidden" value="{{ $product->name }}" class="form-control name">
                                <div class="col-md-6">
                                    <button class="btn btn-primary add-to-cart"><i class="fa fa-shopping-cart"></i> Add
                                        to Cart
                                    </button>
                                </div>

                            </div>
                        </div>  <!-- End of /.products -->
                    </div>
            @endforeach <!-- End Of /.Col-md-3 -->
            </div>  <!-- End of /.row -->
        </div>  <!-- End of /.container -->
    </section>  <!-- End of Section -->


@endsection

    
   

        

resources/views/home/order_success.blade.php
@extends('layouts.frontend')

@section('content')




    <!-- PRODUCTS Start
================================================== -->

    <section id="products">
        <div class="container">
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav nav-main">
                    <li class="{{ Request::segment(1) === 'home' || Request::segment(1) == '' ? 'active' : null }}"><a
                                href="{{ route('home.index')}}">Home</a></li>
                    @foreach ($types as $type)


                        <li class="{{ Request::segment(2) == $type->id ? 'active' : null }}">
                            <a href="{!! route('home.category', [$type->id]) !!}">{{ $type->name }}</a>
                        </li>
                    @endforeach
                </ul> <!-- End of /.nav-main -->
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="products-heading">
                        <br>
                        <h4>NEW PRODUCTS</h4>
                    </div>
                </div>
            </div>
            <div class="row">
                <br>
                @foreach ($products as $product)
                    <div class="col-md-3">
                        <div class="panel panel-default">
                            <a href="{{ route('frontend.show',$product->id)}}">
                                <img src="{{asset($product->image)}}" width="200" height="150">
                            </a>
                            <a href="{{ route('frontend.show',$product->id)}}">
                                <h4>{!! $product->name !!}</h4>
                            </a>
                            <p class="price">{!! $product->price !!} Ks</p>

                            <div class="row">
                                <div class="col-md-5 col-md-offset-1">
                                    <input type="number" value="1" class="form-control qty"/>

                                </div>
                                <input type="hidden" value="{{ $product->id }}" class="form-control id">
                                <input type="hidden" value="{{ $product->price }}" class="form-control price">
                                <input type="hidden" value="{{ $product->name }}" class="form-control name">
                                <div class="col-md-6">
                                    <button class="btn btn-primary add-to-cart"><i class="fa fa-shopping-cart"></i> Add
                                        to Cart
                                    </button>
                                </div>

                            </div>
                        </div>  <!-- End of /.products -->
                    </div>
            @endforeach <!-- End Of /.Col-md-3 -->
            </div>  <!-- End of /.row -->
        </div>  <!-- End of /.container -->
    </section>  <!-- End of Section -->

    <site style="display: none">
        <table class="table">
            <thead>
            <tr>

                <th scope="col">Order Name</th>
                <th scope="col">Order Price</th>
                <th scope="col">Order Quantity</th>
            </tr>
            </thead>
            <tbody style="padding-left: 20px">
            @foreach($orders as $order)
                @foreach($order as $product)
                <tr>
                    <td>{{ $product['attributes']['name'] }}</td>
                    <td>{{ $product['attributes']['price'] }}</td>
                    <td>{{ $product['quantity'] }}</td>
                </tr>
                    @endforeach
            @endforeach
            <tr>
                <td colspan="2">Ordered Total</td>
                <td>{{ $total }}</td>
            </tr>
            </tbody>
        </table>
    </site>
    <script src="https://unpkg.com/sweetalert2@7.19.3/dist/sweetalert2.all.js"></script>
    <script>
        $('document').ready(function () {
            // var swal_html = '<div class="panel" style="background:aliceblue;font-weight:bold"><div class="panel-heading panel-info text-center btn-info"> <b>Import Status</b> </div> ' +
            //     '<table class="table">\n' +
            //     '        <thead>\n' +
            //     '            <tr>\n' +
            //     '                <th>ID</th>\n' +
            //     '                <th>Name</th>\n' +
            //     '                <th>Salary</th>\n' +
            //     '                <th>Country</th>\n' +
            //     '                <th>City</th>\n' +
            //     '            </tr>\n' +
            //     '        </thead>\n' +
            //     '        <tbody>\n' +
            //     '            <tr>\n' +
            //     '                <td>1</td>\n' +
            //     '                <td>Dakota Rice</td>\n' +
            //     '                <td>$36,738</td>\n' +
            //     '                <td>Niger</td>\n' +
            //     '                <td>Oud-Turnhout</td>\n' +
            //     '            </tr>\n' +
            //     '            <tr>\n' +
            //     '                <td>2</td>\n' +
            //     '                <td>Minerva Hooper</td>\n' +
            //     '                <td>$23,789</td>\n' +
            //     '                <td>Curaçao</td>\n' +
            //     '                <td>Sinaai-Waas</td>\n' +
            //     '            </tr>\n' +
            //     '            <tr>\n' +
            //     '                <td>3</td>\n' +
            //     '                <td>Sage Rodriguez</td>\n' +
            //     '                <td>$56,142</td>\n' +
            //     '                <td>Netherlands</td>\n' +
            //     '                <td>Baileux</td>\n' +
            //     '            </tr>\n' +
            //     '            <tr>\n' +
            //     '                <td>4</td>\n' +
            //     '                <td>Philip Chaney</td>\n' +
            //     '                <td>$38,735</td>\n' +
            //     '                <td>Korea, South</td>\n' +
            //     '                <td>Overland Park</td>\n' +
            //     '            </tr>\n' +
            //     '</tbody>\n' +
            //     '</table>';
            // var markup = document.getElementsByTagName('site')[0].innerHTML;
            //   alert(markup);
            //   swal({title:"Success!", customClass: 'swal-wide', html: swal_html}).then(function(){ window.location.href = 'http://127.0.0.1:1111/test';});
            var html = document.getElementsByTagName('site')[0].innerHTML;
            swal({title: "Success!", customClass: 'swal-wide', html: html}).then(function () {
                window.location.href = 'http://127.0.0.1:8000';
            });

        });
    </script>

@endsection

resources/views/home/search.blade.php
@extends('layouts.frontend')

@section('content')




    <!-- PRODUCTS Start
================================================== -->

    <section id="products">
        <div class="container">
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav nav-main">
                    <li class="{{ Request::segment(1) === 'home' || '/' ? 'active' : null }}"><a href="{{ route('home.index')}}">Home</a></li>
                    @foreach ($types as $type)


                        <li class="{{ Request::segment(2) == $type->id ? 'active' : null }}">
                            <a href="{!! route('home.category', [$type->id]) !!}">{{ $type->name }}</a>
                        </li>
                    @endforeach
                </ul> <!-- End of /.nav-main -->
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="products-heading">
                        <br>
                        <h4>Result Found PRODUCTS</h4>
                    </div>
                </div>
            </div>
            <div class="row">
                <br>
                @foreach ($products as $product)
                    <div class="col-md-3">
                        <div class="panel panel-default">
                            <a href="{{ route('frontend.show',$product->id)}}">
                                <img src="{{asset($product->image)}}" width="200" height="150">
                            </a>
                            <a href="{{ route('frontend.show',$product->id)}}">
                                <h4>{!! $product->name !!}</h4>
                            </a>
                            <p class="price">{!! $product->price !!} Ks</p>

                            <div class="row">
                                <div class="col-md-5 col-md-offset-1">
                                    <input type="number" value="1" class="form-control qty"/>

                                </div>
                                <input type="hidden" value="{{ $product->id }}" class="form-control id">
                                <input type="hidden" value="{{ $product->price }}" class="form-control price">
                                <input type="hidden" value="{{ $product->name }}" class="form-control name">
                                <div class="col-md-6">
                                    <button class="btn btn-primary add-to-cart"><i class="fa fa-shopping-cart"></i> Add
                                        to Cart
                                    </button>
                                </div>

                            </div>
                        </div>  <!-- End of /.products -->
                    </div>
            @endforeach <!-- End Of /.Col-md-3 -->
            </div>  <!-- End of /.row -->
        </div>  <!-- End of /.container -->
    </section>  <!-- End of Section -->


@endsection

resources/views/home/user.blade.php
<!DOCTYPE html>

<html lang="en">

<head>

  <title>Okkar Thiri</title>

  <meta charset="utf-8">

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</head>

<body>

 
<div class="container">
	<br>

  <h2>Product Detail Description</h2>

  <div class="card">

    <div class="card-header" align="center">{!! $products->name !!}</div>

    <div class="card-body">
    	<div class="container" align="center">
    		<img src="{{asset($products->image)}}">
    	</div>
    </div> 

    
		<div class="container" align="center">
    		<b>Price      :</b>  {!! $products->price !!}
    		<br>
    		<b>Category :</b>{!! $products->types['name'] !!}

    		<br>
    		<b>Description :</b> <p> {!! $products->description !!}</p>

    	</div>
    <div class="card-footer">
      <div class="container" align="center">
      	<a href="{!! route('home.index') !!}" class="btn btn-info">Back</a>
      </div>	
    	
    </div>

  </div>

</div>

​

</body>

</html>

​

resources/views/home/user_edit.blade.php
@extends('layouts.frontend')

@section('content')
   <br>
    <div class="container">
    <form action="{{ route('update') }}" method="post">
        @csrf
        <input type="hidden" name="id" value="{{ $user->id }}">
        
        <div class="form-group row">
            <label for="inputPassword3" class="col-sm-2 col-sm-offset-2 col-form-label">Name</label>
            <div class="col-sm-8 ">
                <input type="text" class="form-control" id="inputPassword3" name="name" value="{{ $user->name }}">
            </div>
        </div>
         <div class="form-group row">
            <label for="inputPassword3" class="col-sm-2 col-sm-offset-2 col-form-label">Address</label>
            <div class="col-sm-8 ">
                <input type="text" class="form-control" id="inputPassword3" name="address" value="{{ $user->address }}">
            </div>
        </div>
         <div class="form-group row">
            <label for="inputPassword3" class="col-sm-2 col-sm-offset-2 col-form-label">Phone Number</label>
            <div class="col-sm-8 ">
                <input type="text" class="form-control" id="inputPassword3" name="phone" value="{{ $user->phone }}">
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-8 col-sm-offset-2">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </form>
    </div>
@endsection