routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('/');

Route::resource('frontend','HomeController');
Route::get('add','Cart\CartController@addToCart')->name('home.add');


Auth::routes();

Route::get('show', 'HomeController@show')->name('home.show');


Route::resource('categories', 'CategoryController')->middleware('admin');
Route::resource('products', 'ProductController')->middleware('admin');
Route::post('products/search','ProductController@search')->name('products.search');


Route::resource('types', 'TypeController')->middleware('admin');


Route::any('cart', 'Cart\CartController@addTocart')->name('cart.index');
Route::any('category/cart', 'Cart\CartController@addTocart')->name('cart.index');

Route::any('cartToOrder', 'Cart\CartController@cartToOrder')->name('cart.order');

Route::get('orders', 'Cart\CartController@order')->name('orders.index')->middleware('admin');

Route::post('orders/complete', 'Cart\CartController@complete')->name('orders.complete')->middleware('admin');

Route::post('orders/delete', 'Cart\CartController@delete')->name('orders.delete')->middleware('admin');


Route::get('customers','Auth\RegisterController@index')->name('customers.index');


Route::resource('users','Auth\RegisterController');
Route::resource('home','HomeController');
Route::any('category/{id}','HomeController@category')->name('home.category');

Route::post('search', "HomeController@search")->name('search');

Route::post('user/edit','HomeController@useredit')->name('/edit');
Route::post('user/update','HomeController@userupdate')->name('update');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{

	public $fillable = [
        'name',
        'image',
		'description',
		'price',
		'code',
        'type_id',
        'quantity'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name',
        'image',
        'description',
        'price',
        'code',
        'type_id',
        'quantity'
    ];

    public function types()
    {
        return $this->belongsTo(Type::class,'type_id');
    }
   
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UpdateProductRequest;
use App\Models\Product;
use App\Models\Type;
use Illuminate\Http\Request;
use App\Repositories\TypeRepository;
use Laracasts\Flash\Flash;
use App\Repositories\ProductRepository;



class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    private $productRepository;
    private $typeRepository;


    public function __construct(TypeRepository $typeRepo,ProductRepository $productRepo)
    {
        $this->typeRepository = $typeRepo;
        $this->productRepository = $productRepo;
    } 

    public function index()
    {
        $products = Product::with('types')->paginate(10);
        return view('products.index',compact('products'))->withId('');

        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
    $types  =Type::pluck('name', 'id');
    return view('products.create',compact('types'));       
  
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
          $this->validate($request, [
            'name' => 'required',
            'code' => 'required',
            'description' => 'required',
            'type' => 'required',
            'price' => 'required',
             'image' => 'required',
              'quantity' => 'required'
        ]);
        $image = $request->file('image');
        $destinationPath = 'uploads';
        $img_path=$image->move($destinationPath,$image->getClientOriginalName());

        $data = [
            'name'       => $request->get('name'),
            'code'       => $request->get('code'),
            'description'=> $request->get('description'),
            'type_id'    => $request->get('type'),
            'price'      => $request->get('price'),
            'image'      => $img_path,
            'quantity'  => $request->get('quantity')

        ];
        $this->productRepository->create( $data );
        return redirect()->route('products.index')->with(['flash_success' => 'Successfully created.']);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         $products = $this->productRepository->getById($id);

        return view('products.show', compact('products'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $products = $this->productRepository->getById($id);
        $types  =Type::pluck('name', 'id');
        return view('products.edit',compact('types', 'products'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update($id, UpdateProductRequest $request)
    {

        $product = $this->productRepository->find($id);

        if (empty($product)) {
            Flash::error('Product not found');

            return redirect(route('products.index'));
        }
        $image = $request->file('image');
        $destinationPath = 'uploads';
        $img_path=$image->move($destinationPath,$image->getClientOriginalName());

        $data = [
            'name'       => $request->get('name'),
            'code'       => $request->get('code'),
            'description'=> $request->get('description'),
            'type_id'    => $request->get('type'),
            'price'      => $request->get('price'),
            'image'      => $img_path,
            'quantity'  => $request->get('quantity')

        ];

        $category = $this->productRepository->update($data, $id);

        Flash::success('Product updated successfully.');

        return redirect(route('products.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $product = $this->productRepository->find($id);


        if (empty($product)) {
            Flash::error('Product not found');

            return redirect(route('products.index'));
        }

        $this->productRepository->delete($id);

        Flash::success('Product deleted successfully.');

        return redirect(route('products.index'));
    }

    public function search(Request $request)
        {          
   
            $input = $request->all();
                
            $products = Product::where('name', 'LIKE', '%' . $input['search'] . '%')->paginate(10);
             return view('products.index',compact('products'))->withId('');             


            }
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Product
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    <form action="{{ route('products.store') }}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                       <!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    <input type="text" name="name"  class="form-control" required>

</div>
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Code:') !!}
    <input type="text" name="code"  class="form-control" required>

</div>
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Price:') !!}
    <input type="text" name="price"  class="form-control" required>

</div>

<div class="form-group col-sm-6">
    {!! Form::label('name', 'Description:') !!}
   <input type="text" name="description"  class="form-control" required>

</div>


<div class="form-group col-sm-6">

    {{ Form::label('Choose Category:') }}
    <br>



     {!! Form::select('type',$types,['id'=>'type','class'=>'form-control']) !!}

</div>
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Image:') !!}
    <input type="file" name="image" required="">
</div>

<div class="form-group col-sm-6">
    {!! Form::label('name', 'Quantity:') !!}
    <input type="number" name="quantity" class="form-control" required>

</div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    <a href="{!! route('products.index') !!}" class="btn btn-default">Back</a>
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}


</div>


                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Products
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($products, ['route' => ['products.update', $products->id], 'method' => 'patch','files' => true]) !!}

                        @include('products.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/products/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    <input type="text" name="name" value ="{{$products->name}}" class="form-control" required>

</div>
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Code:') !!}
    <input type="text" name="code" value ="{{$products->code}}" class="form-control" required>

</div>
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Price:') !!}
    <input type="text" name="price" value ="{{$products->price}}" class="form-control" required>

</div>

<div class="form-group col-sm-6">
    {!! Form::label('name', 'Description:') !!}
   <input type="text" name="description" value ="{{$products->description}}" class="form-control" required>

</div>


<div class="form-group col-sm-6">

    {{ Form::label('Choose Category:') }}
    <br>



     {!! Form::select('type',$types,['id'=>'type','class'=>'form-control']) !!}

</div>
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Image:') !!}
    <input type="file" name="image" required="">
</div>

<div class="form-group col-sm-6">
    {!! Form::label('name', 'Quantity:') !!}
    <input type="number" name="quantity" value ="{{$products->quantity}}" class="form-control" required>

</div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    <a href="{!! route('products.index') !!}" class="btn btn-default">Back</a>
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}


</div>

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Products</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('products.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('products.table')
            </div>
        </div>
    
    </div>

    {{ $products->render("pagination::bootstrap-4") }} 
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Type
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('products.show_fields')
                    <a href="{!! route('products.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/show_fields.blade.php
<!-- Id Field -->


<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $products->name !!}</p>
</div>
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $products->code !!}</p>
</div>
<div class="form-group">
    {!! Form::label('name', 'Category:') !!}
    <p>{!! $products->types['name'] !!}</p>
</div>
<div class="form-group">
    {!! Form::label('name', 'Description:') !!}
    <p>{!! $products->description !!}</p>
</div>
<div class="form-group">
    {!! Form::label('name', 'Price:') !!}
    <p>{!! $products->price !!}</p>
</div>
<div class="form-group">
    {!! Form::label('name', 'Quantity:') !!}
    <p>{!! $products->quantity !!}</p>
</div>
<div class="form-group">
<img src="{{asset($products->image)}}">
</div>

resources/views/products/table.blade.php
<table class="table table-responsive" id="products-table">
    <thead>
    <tr>
        <th>code</th>
        <th>Name</th>
        <th>Category</th>
        <th>description</th>
        <th>price</th>
        <th>quantity</th>

        <th colspan="3">Action</th>
    </tr>
    </thead>
    <tbody>
    @foreach($products as $product)
        <tr>
            <td>{!! $product->code !!}</td>
            <td>{!! $product->name !!}</td>
            <td>{!! $product->types['name'] !!}</td>
            <td>{!! $product->description !!}</td>
            <td>{!! $product->price !!}</td>
            <td>{!! $product->quantity !!}</td>
            <td>
                {!! Form::open(['route' => ['products.destroy', $product->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('products.show', [$product->id]) !!}" class='btn btn-default btn-xs'><i
                                class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('products.edit', [$product->id]) !!}" class='btn btn-default btn-xs'><i
                                class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>