routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('/');

Route::resource('frontend','HomeController');
Route::get('add','Cart\CartController@addToCart')->name('home.add');


Auth::routes();

Route::get('show', 'HomeController@show')->name('home.show');


Route::resource('categories', 'CategoryController')->middleware('admin');
Route::resource('products', 'ProductController')->middleware('admin');
Route::post('products/search','ProductController@search')->name('products.search');


Route::resource('types', 'TypeController')->middleware('admin');


Route::any('cart', 'Cart\CartController@addTocart')->name('cart.index');
Route::any('category/cart', 'Cart\CartController@addTocart')->name('cart.index');

Route::any('cartToOrder', 'Cart\CartController@cartToOrder')->name('cart.order');

Route::get('orders', 'Cart\CartController@order')->name('orders.index')->middleware('admin');

Route::post('orders/complete', 'Cart\CartController@complete')->name('orders.complete')->middleware('admin');

Route::post('orders/delete', 'Cart\CartController@delete')->name('orders.delete')->middleware('admin');


Route::get('customers','Auth\RegisterController@index')->name('customers.index');


Route::resource('users','Auth\RegisterController');
Route::resource('home','HomeController');
Route::any('category/{id}','HomeController@category')->name('home.category');

Route::post('search', "HomeController@search")->name('search');

Route::post('user/edit','HomeController@useredit')->name('/edit');
Route::post('user/update','HomeController@userupdate')->name('update');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Admin | Okkar Thiri</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <!-- Theme style -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/AdminLTE.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/skins/_all-skins.min.css">

    <!-- iCheck -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/square/_all.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css">

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">

    @yield('css')

</head>

<body class="skin-blue sidebar-mini">
@if (!Auth::guest())
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">

            <!-- Logo -->
            <a href="#" class="logo">
                <b>Okkar Thiri Admin</b>
            </a>

            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg"
                                     class="user-image" alt="User Image"/>
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">{!! Auth::user()->name !!}</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <img src="http://infyom.com/images/logo/blue_logo_150x150.jpg"
                                         class="img-circle" alt="User Image"/>
                                    <p>
                                        {!! Auth::user()->name !!}
                                        <small>Member since {!! Auth::user()->created_at->format('M. Y') !!}</small>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">

                                    <div class="pull">
                                        <a href="{!! url('/logout') !!}" class="btn btn-default btn-flat"
                                           onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                            Sign out
                                        </a>
                                        <form id="logout-form" action="{{ url('/logout') }}" method="GET"
                                              style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
    @include('layouts.sidebar')
    <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @yield('content')
        </div>

        <!-- Main Footer -->
        <footer class="main-footer" style="max-height: 100px;text-align: center">
            <strong>Copyright © 2019 <a href="#">Okkar Thiri</a>.</strong> All rights reserved.
        </footer>

    </div>
@else
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{!! url('/') !!}">
                    Okkar Thiri Pharmacy
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{!! url('/home') !!}">Home</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    <li><a href="{!! url('/login') !!}">Login</a></li>
                    <li><a href="{!! url('/register') !!}">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
@endif


<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>

<!-- jQuery 3.1.1 -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<!-- AdminLTE App -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/js/adminlte.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>

@yield('scripts')
<script>
    $('.complete-confirm').on('click', function () {
        // var postID = $(this).val();

        var $btn = $(this);

        var postID = $btn.parent().parent().find('.id').val();

        swal({
            title: "Are you sure?",
            text: "To complete customer ordered Item.",
            type: "warning",
            showCancelButton: true,
            closeOnConfirm: false,
            showLoaderOnConfirm: true,
            confirmButtonClass: "btn-danger",
            confirmButtonText: "Yes, complete it!",
        }, function () {
            setTimeout(function () {
                $.post("orders/complete", {
                        id: postID
                    },
                    function (data, status) {
                        swal({
                                title: "Completed!",
                                text: "Your post has been completed.",
                                type: "success"
                            },
                            function () {
                                location.reload();
                            }
                        );
                    }
                );

            }, 50);
        });
    });
</script>
<script>
    $('.delete-confirm').on('click', function () {
        var $btn = $(this);

        var postID = $btn.parent().parent().find('.id').val();
        console.log(postID);
        swal({
            title: "Are you sure?",
            text: "If you delete this post all associated comments also deleted permanently.",
            type: "warning",
            showCancelButton: true,
            closeOnConfirm: false,
            showLoaderOnConfirm: true,
            confirmButtonClass: "btn-danger",
            confirmButtonText: "Yes, delete it!",
        }, function () {
            setTimeout(function () {
                $.post("orders/delete", {
                        id: postID
                    },
                    function (data, status) {
                        swal({
                                title: "Deleted!",
                                text: "Your post has been deleted.",
                                type: "success"
                            },
                            function () {
                                location.reload();
                            }
                        );
                    }
                );

            }, 50);
        });
    });
</script>

</body>
</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/frontend.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Okkar Thiri</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Yanone+Kaffeesatz:400,700' rel='stylesheet' type='text/css'>

    <!-- Css -->
    <link rel="stylesheet" href="{{asset('css/nivo-slider.css')}}" type="text/css"/>
    <link rel="stylesheet" href="{{asset('css/owl.carousel.css')}}">
    <link rel="stylesheet" href="{{asset('css/owl.theme.css')}}">
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/font-awesome.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
    <link rel="stylesheet" href="{{asset('css/responsive.css')}}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">

    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

    <!-- Theme style -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/AdminLTE.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/skins/_all-skins.min.css">

    <!-- iCheck -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/square/_all.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css">

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css">
<style>
    .swal-wide{
        width:500px !important;
    }
</style>
    <!-- jS -->

    <script src="{{ asset('js/jquery.min.js')}}" type="text/javascript"></script>
    <script src="{{ asset('js/bootstrap.min.js')}}" type="text/javascript"></script>
    <script src="{{ asset('js/jquery.nivo.slider.js')}}" type="text/javascript"></script>
    <script src="{{ asset('js/jquery.nicescroll.js')}}" type="text/javascript"></script>
    <script src="{{ asset('js/jquery.scrollUp.min.js')}}"></script>
    <script src="{{ asset('js/main.js" type="text/javascript')}}"></script>
    <script src="{{ asset('js/components/pizza.js')}}"></script>


</head>
<body>


<!-- TOP HEADER Start
    ================================================== -->

<section id="top">
    <div class="container">
        <div class="container">
            <div class="row">
                <div class="row">
                    <div class="col-md-4">
                        <p class="contact-action">
                        <h1><a href="{{ route('home.index')}}">Okkar Thiri</a></h1></p>
                    </div><!-- logo  -->
                    <div class="col-md-3">
                        <br>
                        <div class="pull-left">
                            <form action="{!! route('search') !!}" method="post">
                                @csrf
                                <div class="input-group">
                                    <input type="text" name="product" class="form-control" placeholder="Search for..." required/>
                                    <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">Go!</button>
                                </span>
                                </div><!-- /input-group -->
                            </form>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <br>
                        <div class="pull-right">
                            @if (Auth::guest())
                                <a href="login">
                                    <i class="fa fa-user"></i>Login
                                </a>
                            @else

                                <ul class="nav navbar-nav">
                                    <!-- User Account Menu -->
                                    <li class="dropdown user user-menu">
                                        <!-- Menu Toggle Button -->
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                            <!-- The user image in the navbar-->
                                            <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                            <span class="hidden-xs">{!! Auth::user()->name !!}</span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <!-- The user image in the menu -->
                                            <li class="user-header">
                                                <img src="images/index.png"
                                                     class="img-circle" alt="User Image"/>
                                                <br>
                                                <font color="black">  {!! Auth::user()->name !!}
                                                    <br>
                                                    <small>Member
                                                        since {!! Auth::user()->created_at->format('M. Y') !!}</small>
                                                </font>
                                            </li>
                                            <!-- Menu Footer-->
                                            <li class="user-footer">

                                                <div class="pull">
                                                    <a href="{!! url('/logout') !!}"
                                                       class="btn btn-success">
                                                        Sign out
                                                    </a>
                                                    <a href="{!! url('/edit') !!}"
                                                       class="btn btn-default btn-flat pull-right"
                                                       onclick="event.preventDefault(); document.getElementById('edit-form').submit();">
                                                        Edit Profile
                                                    </a>

                                                    <form id="edit-form" action="{{ route('/edit',['id' => Auth::user()->id] ) }}"
                                                          method="POST"
                                                          style="display: none;">
                                                        {{ csrf_field() }}
                                                    </form>
                                                </div>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            @endif
                        </div>
                    </div><!-- cart -->
                    <div class="col-md-2">
                        <br>
                        <div>
                            <a href="{{ route('cart.index',['a' => 'cart'])}}"><i
                                        class="fa fa-shopping-cart"></i>Cart( {{ $total }} )
                            </a>

                        </div>
                    </div><!-- user -->
                </div>
            </div> <!-- End Of /.row -->
        </div>  <!-- End Of /.Container -->


        <!-- MODAL Start
            ================================================== -->


</section>  <!-- End of /Section -->


<!-- LOGO Start
================================================== -->


@if(session()->has('success'))
    <div class="alert alert-success">
        {{ session()->get('success') }}
    </div>
@endif

@if(session()->has('login'))
    <div class="alert alert-info">
        {{ session()->get('login') }}
    </div>
@endif
@yield('content')


<div class="footer-bottom">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h3 align="left">Contact Us</h3>
                <p align="left">
                    No.28, Pyay Road, Hlaing Township, Yangon, Myanmar
                    Yangon
                    <br>
                    Phone:01 500 049


            </div>
            <div class="col-md-6">
            </div> <!-- End Of /.col-md-12 -->
            <div class="row">
                <p class="copyright-text pull-right">OKKAR THIRI @2019 | All Rights Reserved</p>
            </div>
        </div>  <!-- End Of /.row -->
    </div>  <!-- End Of /.container -->
</div>  <!-- End Of /.footer-bottom -->
</footer> <!-- End Of Footer -->

<a id="back-top" href="#"></a>
<script>
    $(document).ready(function () {
        $('.add-to-cart').on('click', function (e) {
            e.preventDefault();

            var $btn = $(this);
            var id = $btn.parent().parent().find('.id').val();
            var color = $btn.parent().parent().find('.color').val() || '';
            var qty = $btn.parent().parent().find('.qty').val();
            var name = $btn.parent().parent().find('.name').val();
            var price = $btn.parent().parent().find('.price').val();


            var $form = $('<form action="cart?a=cart" method="post" />').html('<input type="hidden" name="add" value="1"><input type="hidden" name="price" value="' + price + '"> <input type="hidden" name="name" value="' + name + '"><input type="hidden" name="id" value="' + id + '"><input type="hidden" name="color" value="' + color + '"><input type="hidden" name="qty" value="' + qty + '">');

            $('body').append($form);
            $form.submit();
        });

        $('.btn-update').on('click', function () {
            var $btn = $(this);
            var id = $btn.attr('data-id');
            var qty = $btn.parent().parent().find('.quantity').val();
            var color = $btn.attr('data-color');

            var $form = $('<form action="cart?a=cart" method="post" />').html('<input type="hidden" name="update" value="1"><input type="hidden" name="id" value="' + id + '"><input type="hidden" name="qty" value="' + qty + '"><input type="hidden" name="color" value="' + color + '">');

            $('body').append($form);
            $form.submit();
        });

        $('.btn-remove').on('click', function () {
            var $btn = $(this);
            var id = $btn.attr('data-id');
            var color = $btn.attr('data-color');

            var $form = $('<form action="cart?a=cart" method="post" />').html('<input type="hidden" name="remove" value="1"><input type="hidden" name="id" value="' + id + '"><input type="hidden" name="color" value="' + color + '">');

            $('body').append($form);
            $form.submit();
        });

        $('.btn-empty-cart').on('click', function () {
            var $form = $('<form action="cart?a=cart" method="post" />').html('<input type="hidden" name="empty" value="1">');

            $('body').append($form);
            $form.submit();
        });
    });
</script>

</body>
</html>

resources/views/layouts/menu.blade.php
<li class="{{ Request::is('types*') ? 'active' : '' }}">
    <a href="{!! route('types.index') !!}"><i class="fa fa-edit"></i><span>Categories</span></a>
</li>


<li class="{{ Request::is('products*') ? 'active' : '' }}">
    
    <a href="{!! route('products.index') !!}"><i class="fa fa-edit"></i><span>Products</span></a>
</li>


<li class="{{ Request::is('orders*') ? 'active' : '' }}">

    <a href="{!! route('orders.index') !!}"><i class="fa fa-edit"></i><span>Order</span></a>

</li>

<li>

    <a href="{!! route('customers.index') !!}"><i class="fa fa-edit"></i><span>Customers</span></a>
    
</li>

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar" id="sidebar-wrapper">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            
            <div class="pull-left info">
                @if (Auth::guest())
                <p>Okkar Thiri</p>
                @else
                    <p>{{ Auth::user()->name}}</p>
                @endif
                <!-- Status -->
               
            </div>
        </div>

        <!-- search form (Optional) -->
       
        <!-- Sidebar Menu -->

        <ul class="sidebar-menu" data-widget="tree">
            @include('layouts.menu')
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>