routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('/');

Route::resource('frontend','HomeController');
Route::get('add','Cart\CartController@addToCart')->name('home.add');


Auth::routes();

Route::get('show', 'HomeController@show')->name('home.show');


Route::resource('categories', 'CategoryController')->middleware('admin');
Route::resource('products', 'ProductController')->middleware('admin');
Route::post('products/search','ProductController@search')->name('products.search');


Route::resource('types', 'TypeController')->middleware('admin');


Route::any('cart', 'Cart\CartController@addTocart')->name('cart.index');
Route::any('category/cart', 'Cart\CartController@addTocart')->name('cart.index');

Route::any('cartToOrder', 'Cart\CartController@cartToOrder')->name('cart.order');

Route::get('orders', 'Cart\CartController@order')->name('orders.index')->middleware('admin');

Route::post('orders/complete', 'Cart\CartController@complete')->name('orders.complete')->middleware('admin');

Route::post('orders/delete', 'Cart\CartController@delete')->name('orders.delete')->middleware('admin');


Route::get('customers','Auth\RegisterController@index')->name('customers.index');


Route::resource('users','Auth\RegisterController');
Route::resource('home','HomeController');
Route::any('category/{id}','HomeController@category')->name('home.category');

Route::post('search', "HomeController@search")->name('search');

Route::post('user/edit','HomeController@useredit')->name('/edit');
Route::post('user/update','HomeController@userupdate')->name('update');

app/Models/Order.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $table = 'orderdetails';

    public $fillable = [
        'user_id',
        'order_price',
        'order_quantity',
        'order_status',
        'order_total',
        'order_name'
    ];

    public function users()
    {
        return $this->belongsTo(User::class,'user_id');
    }
}

resources/views/order/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Order</h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                @include('order.table')
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection

resources/views/order/table.blade.php
<table class="table table-responsive" id="products-table">
    <thead>
    <tr>
        <th>Customer Name</th>
        <th>Item</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total</th>
        <th>Status</th>

        <th colspan="3">Action</th>
    </tr>
    </thead>
    <tbody>
    @foreach($orders as $order)
        <tr>
            <td><a href="{!! route('users.show', [$order->users->id]) !!}" > {!! $order->users->name !!}</a></td>
            <td>{!! $order->order_name !!}</td>
            <td>{!! $order->order_price !!}</td>
            <td>{!! $order->order_quantity !!}</td>
            <td>{!! $order->order_total !!}</td>
            <td>
                @if($order->order_status == 1)
                <span class="label label-success">Delivered</span>
                    @else
                    <span class="label label-warning">Pending</span>
                    @endif

            </td>
            <td>

                    <div class='btn btn-default btn-xs complete-confirm'>Complete
                        <input type="hidden" value="{{ $order->id }}" class="id">
                        <i class="glyphicon glyphicon-edit"></i></div>
                    <!-- <div class='btn btn-default btn-xs delete-confirm'>
                        <input type="hidden" value="{{ $order->id }}" class="id">
                        <i class="glyphicon glyphicon-trash"></i></div> -->

            </td>
        </tr>
    @endforeach
    </tbody>
</table>